# Generated by Django 5.2.4 on 2026-07-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_text_and_image_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='source_chunks',
            field=models.JSONField(blank=True, default=list, help_text='List of chunk indexes used for context'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds for audio or video', null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='True when chunks and embeddings are ready'),
        ),
    ]
