# Generated by Django 6.0.5 on 2026-05-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='referenced_timestamp',
            field=models.FloatField(blank=True, help_text='Suggested playback time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_dimensions',
            field=models.IntegerField(default=1536, editable=False),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='end_time',
            field=models.FloatField(blank=True, help_text='End time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='start_time',
            field=models.FloatField(blank=True, help_text='Start time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds (for audio/video)', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='source_chunks',
            field=models.JSONField(blank=True, default=list, help_text='List of chunk IDs used for context'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(help_text='Order of chunk in document'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(help_text='Local path or cloud URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='True when chunks & embeddings are ready'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary', null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['file', 'start_time'], name='api_documen_file_id_start_idx'),
        ),
    ]
